name: Automerge

on:
  pull_request:

jobs:
  auto-merge:
    if: "contains(github.event.pull_request.labels.*.name, 'autorelease: pending')"
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_FILTER_AUTHOR: "itsHenry35"
