name: Debug

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  Build_Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.6
         
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      
      - name: Build and rename the artifact
        run: |
          pyinstaller --noconfirm --onefile --console --icon "D:/a/ledu/ledu/ledu.ico" --add-data "D:/a/ledu/ledu/bin/aria2c_win32_x64.exe;bin/" --add-data "D:/a/ledu/ledu/bin/aria2_win32.conf;bin/"  "D:/a/ledu/ledu/main.py"
          $SHORT_COMMIT_ID = $env:GITHUB_SHA.Substring(0,7)
          if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
            $FILENAME = "ledu_download_win64_PR_$($SHORT_COMMIT_ID).exe"
          } else {
            $FILENAME = "ledu_download_win64_$($SHORT_COMMIT_ID).exe"
          }
          ren D:\a\ledu\ledu\dist\main.exe D:\a\ledu\ledu\dist\$FILENAME
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "Windows-build"
          path: "D:\\a\\ledu\\ledu\\dist"
          
  Build_Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.6
         
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      
      - name: Build and rename the artifact
        run: |
          pyinstaller --noconfirm --onefile --console --icon "/home/runner/work/ledu/ledu/ledu.ico" --add-data "/home/runner/work/ledu/ledu/bin/aria2c_linux_x64:bin/" --add-data "/home/runner/work/ledu/ledu/bin/aria2_linux.conf:bin/" "/home/runner/work/ledu/ledu/main.py"
          SHORT_COMMIT_ID=${GITHUB_SHA::7}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            FILENAME=ledu_download_linux_amd64_pr_$SHORT_COMMIT_ID
          else
            FILENAME=ledu_download_linux_amd64_$SHORT_COMMIT_ID
          fi            
          mv /home/runner/work/ledu/ledu/dist/main /home/runner/work/ledu/ledu/dist/$FILENAME          
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "Linux-build"
          path: "/home/runner/work/ledu/ledu/dist"

  Build_Macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.6
         
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      
      - name: Build and compress the artifact
        run: |
          pyinstaller --noconfirm --onefile --console --icon "/Users/runner/work/ledu/ledu/ledu.ico" --add-data "/Users/runner/work/ledu/ledu/bin/aria2c_darwin_x64:bin/" --add-data "/Users/runner/work/ledu/ledu/bin/aria2_darwin.conf:bin/" "/Users/runner/work/ledu/ledu/main.py"
          SHORT_COMMIT_ID=${GITHUB_SHA::7}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            FILENAME=ledu_download_macos_pr_$SHORT_COMMIT_ID
          else
            FILENAME=ledu_download_macos_$SHORT_COMMIT_ID
          fi             
          mv /Users/runner/work/ledu/ledu/dist/main /Users/runner/work/ledu/ledu/dist/$FILENAME
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "MacOs-build"
          path: "/Users/runner/work/ledu/ledu/dist/"
