# This is a basic workflow to help you get started with Actions

name: Build_Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build_Windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
         
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      
      - name: Build the artifact
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "D:/a/ledu/ledu/ledu.ico" --add-data "D:/a/ledu/ledu/bin/aria2c_win.exe;bin/"  "D:/a/ledu/ledu/main.py"
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: |
              D:\a\ledu\ledu\dist\main.exe
          
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: "Windows-build"
          path: "D:\\a\\ledu\\ledu\\dist"
          
  Build_Linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
         
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      
      - name: Build the artifact
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "/home/runner/ledu/ledu/ledu.ico" --add-data "/home/runner/ledu/bin/aria2c_win.exe;bin/"  "/home/runner/ledu/main.py"
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: |
              /home/runner/ledu/ledu/dist/main
          
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: "Windows-build"
          path: "/home/runner/ledu/ledu/dist"
